
CREATE TABLE CO_SEQUENCE
(
	TABLE_NAME           VARCHAR2(16) NOT NULL ,
	NEXT_ID              NUMBER(30) NOT NULL ,
CONSTRAINT  PK_SEQUENCE PRIMARY KEY (TABLE_NAME)
);



COMMENT ON TABLE CO_SEQUENCE IS '일련번호_생성';



COMMENT ON COLUMN CO_SEQUENCE.TABLE_NAME IS 'TABLE_NAME';
COMMENT ON COLUMN CO_SEQUENCE.NEXT_ID IS 'NEXT_ID';




CREATE TABLE CO_ERR_LOG
(
	SEQ                  NUMBER NOT NULL ,
	TITLE                VARCHAR2(300) NOT NULL ,
	CONTENTS             CLOB NULL ,
	URL                  VARCHAR2(100) NOT NULL ,
	SOLV_YN              CHAR(1) DEFAULT  'N'  NOT NULL ,
	SOLV_DT              DATE NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
CONSTRAINT  PK_ERR_LOG PRIMARY KEY (SEQ)
);



COMMENT ON TABLE CO_ERR_LOG IS '에러_로그';



COMMENT ON COLUMN CO_ERR_LOG.SEQ IS '일련번호';
COMMENT ON COLUMN CO_ERR_LOG.TITLE IS '제목';
COMMENT ON COLUMN CO_ERR_LOG.CONTENTS IS '내용';
COMMENT ON COLUMN CO_ERR_LOG.URL IS 'URL';
COMMENT ON COLUMN CO_ERR_LOG.SOLV_YN IS '해결_여부';
COMMENT ON COLUMN CO_ERR_LOG.SOLV_DT IS '해결_일시';
COMMENT ON COLUMN CO_ERR_LOG.REG_DT IS '등록_일시';




CREATE TABLE CO_MENU
(
	MENU_CD              NUMBER(4) NOT NULL ,
	HIGH_MENU_CD         NUMBER(4) DEFAULT  0  NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	MENU_NM              VARCHAR2(50) NOT NULL ,
	MENU_URL             VARCHAR2(200) NULL ,
	MENU_PATTERN         VARCHAR2(50) NULL ,
	MENU_ID              VARCHAR2(40) NULL ,
	MENU_ICON            VARCHAR2(30) NULL ,
	DIVIDER_YN           CHAR(1) DEFAULT  'N'  NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_MENU PRIMARY KEY (MENU_CD),
CONSTRAINT FK_MENU_HIGH_MENU_CD FOREIGN KEY (HIGH_MENU_CD) REFERENCES CO_MENU (MENU_CD) ON DELETE CASCADE
);



COMMENT ON TABLE CO_MENU IS '메뉴';



COMMENT ON COLUMN CO_MENU.MENU_CD IS '메뉴_코드';
COMMENT ON COLUMN CO_MENU.HIGH_MENU_CD IS '상위_메뉴_코드';
COMMENT ON COLUMN CO_MENU.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_MENU.MENU_NM IS '메뉴_명';
COMMENT ON COLUMN CO_MENU.MENU_URL IS '메뉴_URL';
COMMENT ON COLUMN CO_MENU.MENU_PATTERN IS '메뉴_패턴';
COMMENT ON COLUMN CO_MENU.MENU_ID IS '메뉴_아이디';
COMMENT ON COLUMN CO_MENU.MENU_ICON IS '메뉴_아이콘';
COMMENT ON COLUMN CO_MENU.DIVIDER_YN IS '구분선_여부';
COMMENT ON COLUMN CO_MENU.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_MENU.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_MENU.MODI_DT IS '수정_일시';




CREATE TABLE CO_AUTH
(
	AUTH_CD              NUMBER(4) NOT NULL ,
	AUTH_NM              VARCHAR2(50) NOT NULL ,
	AUTH_DESC            VARCHAR2(200) NULL ,
	MANAGE_YN            CHAR(1) DEFAULT  'Y'  NULL ,
	SHOW_YN              CHAR(1) DEFAULT  'Y'  NULL ,
CONSTRAINT  PK_AUTH PRIMARY KEY (AUTH_CD)
);



COMMENT ON TABLE CO_AUTH IS '권한';



COMMENT ON COLUMN CO_AUTH.AUTH_CD IS '권한_코드';
COMMENT ON COLUMN CO_AUTH.AUTH_NM IS '권한_명';
COMMENT ON COLUMN CO_AUTH.AUTH_DESC IS '권한_설명';
COMMENT ON COLUMN CO_AUTH.MANAGE_YN IS '관리대상_여부';
COMMENT ON COLUMN CO_AUTH.SHOW_YN IS '표시_여부';




CREATE TABLE CO_USER
(
	USER_KEY             VARCHAR2(100) NOT NULL ,
	TYPE_CD              VARCHAR2(20) DEFAULT  '-1'  NULL ,
	USER_ID              VARCHAR2(50) NULL ,
	USER_NM              VARCHAR2(50) NOT NULL ,
	USER_ENC_PWD         VARCHAR2(100) NULL ,
	USER_ENC_TEL_NUM     VARCHAR2(100) NULL ,
	USER_ENC_MOBILE      VARCHAR2(100) NULL ,
	USER_ENC_EMAIL       VARCHAR2(200) NULL ,
	POST_CD              VARCHAR2(7) NULL ,
	ADDR1                VARCHAR2(200) NULL ,
	ADDR2                VARCHAR2(200) NULL ,
	ROAD_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_USER PRIMARY KEY (USER_KEY)
);



COMMENT ON TABLE CO_USER IS '사용자';



COMMENT ON COLUMN CO_USER.USER_KEY IS '사용자_KEY';
COMMENT ON COLUMN CO_USER.TYPE_CD IS '유형_코드';
COMMENT ON COLUMN CO_USER.USER_ID IS '사용자_아이디';
COMMENT ON COLUMN CO_USER.USER_NM IS '사용자_명';
COMMENT ON COLUMN CO_USER.USER_ENC_PWD IS '사용자_암호화_비밀번호';
COMMENT ON COLUMN CO_USER.USER_ENC_TEL_NUM IS '사용자_암호화_전화_번호';
COMMENT ON COLUMN CO_USER.USER_ENC_MOBILE IS '사용자_암호화_휴대폰';
COMMENT ON COLUMN CO_USER.USER_ENC_EMAIL IS '사용자_암호화_이메일';
COMMENT ON COLUMN CO_USER.POST_CD IS '우편번호';
COMMENT ON COLUMN CO_USER.ADDR1 IS '기본주소';
COMMENT ON COLUMN CO_USER.ADDR2 IS '상세주소';
COMMENT ON COLUMN CO_USER.ROAD_YN IS '도로명_여부';
COMMENT ON COLUMN CO_USER.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_USER.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_USER.MODI_DT IS '수정_일시';




CREATE TABLE CO_DEPT
(
	DEPT_CD              VARCHAR2(20) NOT NULL ,
	HIGH_DEPT_CD         VARCHAR2(20) DEFAULT  '0'  NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	DEPT_NM              VARCHAR2(100) NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	BRANCH_CD            VARCHAR2(20) NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_DEPT PRIMARY KEY (DEPT_CD),
CONSTRAINT FK_DEPT_HIGH_DEPT_CD FOREIGN KEY (HIGH_DEPT_CD) REFERENCES CO_DEPT (DEPT_CD) ON DELETE CASCADE,
CONSTRAINT FK_DEPT_BRANCH_CD FOREIGN KEY (BRANCH_CD) REFERENCES CO_DEPT (DEPT_CD)
);



COMMENT ON TABLE CO_DEPT IS '부서';



COMMENT ON COLUMN CO_DEPT.DEPT_CD IS '부서_코드';
COMMENT ON COLUMN CO_DEPT.HIGH_DEPT_CD IS '상위_부서_코드';
COMMENT ON COLUMN CO_DEPT.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_DEPT.DEPT_NM IS '부서_명';
COMMENT ON COLUMN CO_DEPT.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_DEPT.BRANCH_CD IS '부점_코드';
COMMENT ON COLUMN CO_DEPT.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_DEPT.MODI_DT IS '수정_일시';




CREATE TABLE CO_MGR
(
	MGR_ID               VARCHAR2(20) NOT NULL ,
	DEPT_CD              VARCHAR2(20) NOT NULL ,
	MGR_NM               VARCHAR2(60) NOT NULL ,
	MGR_ENC_PWD          VARCHAR2(100) NOT NULL ,
	GRADE_NM             VARCHAR2(100) NULL ,
	ROLE_NM              VARCHAR2(500) NULL ,
	TEL_NUM              VARCHAR2(20) NULL ,
	FAX_NUM              VARCHAR2(20) NULL ,
	MOBILE               VARCHAR2(20) NULL ,
	EMAIL                VARCHAR2(100) NULL ,
	PHOTO                VARCHAR2(200) NULL ,
	LOGIN_CNT            NUMBER DEFAULT  0  NOT NULL ,
	LOGIN_DT             DATE NULL ,
	ALIM_YN              CHAR(1) DEFAULT  'N'  NOT NULL ,
	EMAIL_YN             CHAR(1) DEFAULT  'N'  NOT NULL ,
	SMS_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	CONN_ID              VARCHAR2(40) NULL ,
	THEME                VARCHAR2(20) NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_MGR PRIMARY KEY (MGR_ID),
CONSTRAINT FK_MGR_DEPT_CD FOREIGN KEY (DEPT_CD) REFERENCES CO_DEPT (DEPT_CD) ON DELETE CASCADE
);



COMMENT ON TABLE CO_MGR IS '담당자';



COMMENT ON COLUMN CO_MGR.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_MGR.DEPT_CD IS '부서_코드';
COMMENT ON COLUMN CO_MGR.MGR_NM IS '담당자_명';
COMMENT ON COLUMN CO_MGR.MGR_ENC_PWD IS '담당자_암호화_비밀번호';
COMMENT ON COLUMN CO_MGR.GRADE_NM IS '직급_명';
COMMENT ON COLUMN CO_MGR.ROLE_NM IS '역할_명';
COMMENT ON COLUMN CO_MGR.TEL_NUM IS '전화_번호';
COMMENT ON COLUMN CO_MGR.FAX_NUM IS '팩스_번호';
COMMENT ON COLUMN CO_MGR.MOBILE IS '휴대폰';
COMMENT ON COLUMN CO_MGR.EMAIL IS '이메일';
COMMENT ON COLUMN CO_MGR.PHOTO IS '사진';
COMMENT ON COLUMN CO_MGR.LOGIN_CNT IS '로그인_건수';
COMMENT ON COLUMN CO_MGR.LOGIN_DT IS '로그인_일시';
COMMENT ON COLUMN CO_MGR.ALIM_YN IS '알림_여부';
COMMENT ON COLUMN CO_MGR.EMAIL_YN IS '이메일_여부';
COMMENT ON COLUMN CO_MGR.SMS_YN IS 'SMS_여부';
COMMENT ON COLUMN CO_MGR.CONN_ID IS '연계_아이디';
COMMENT ON COLUMN CO_MGR.THEME IS '테마';
COMMENT ON COLUMN CO_MGR.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_MGR.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_MGR.MODI_DT IS '수정_일시';




CREATE TABLE CO_USER_LOG
(
	USER_KEY             VARCHAR2(100) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	LOG_CONTENTS         VARCHAR2(1000) NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
CONSTRAINT  PK_USER_LOG PRIMARY KEY (USER_KEY,ORDER_NO),
CONSTRAINT FK_USER_LOG_USER_KEY FOREIGN KEY (USER_KEY) REFERENCES CO_USER (USER_KEY) ON DELETE CASCADE,
CONSTRAINT FK_USER_LOG_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_USER_LOG IS '사용자_로그';



COMMENT ON COLUMN CO_USER_LOG.USER_KEY IS '사용자_KEY';
COMMENT ON COLUMN CO_USER_LOG.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_USER_LOG.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_USER_LOG.LOG_CONTENTS IS '로그_내용';
COMMENT ON COLUMN CO_USER_LOG.REG_DT IS '등록_일시';




CREATE TABLE CO_CACHE_RELOAD_LOG
(
	SEQ                  NUMBER NOT NULL ,
	IP_ADDR              VARCHAR2(50) NOT NULL ,
	CLASS_NM             VARCHAR2(50) NOT NULL ,
	RELOAD_DT            DATE NULL ,
CONSTRAINT  PK_CACHE_RELOAD_LOG PRIMARY KEY (SEQ)
);



COMMENT ON TABLE CO_CACHE_RELOAD_LOG IS '캐쉬_RELOAD_로그';



COMMENT ON COLUMN CO_CACHE_RELOAD_LOG.SEQ IS '일련번호';
COMMENT ON COLUMN CO_CACHE_RELOAD_LOG.IP_ADDR IS 'IP_주소';
COMMENT ON COLUMN CO_CACHE_RELOAD_LOG.CLASS_NM IS 'CLASS_명';
COMMENT ON COLUMN CO_CACHE_RELOAD_LOG.RELOAD_DT IS 'RELOAD_일시';




CREATE TABLE CO_BBS_CONF
(
	BBS_CD               NUMBER(4) NOT NULL ,
	BBS_NM               VARCHAR2(200) NOT NULL ,
	TYPE_CD              VARCHAR2(20) DEFAULT  '-1'  NULL ,
	FOLDER_NM            VARCHAR2(50) NOT NULL ,
	TABLE_NM             VARCHAR2(100) NULL ,
	CMT_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	CTG_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	FILE_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	FILE_CNT             NUMBER(2) DEFAULT  0  NOT NULL ,
	OPEN_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	NTC_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	ADM_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	HTML_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	ALIM_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_BBS_CONF PRIMARY KEY (BBS_CD)
);



COMMENT ON TABLE CO_BBS_CONF IS '게시판_환경';



COMMENT ON COLUMN CO_BBS_CONF.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS_CONF.BBS_NM IS '게시판_명';
COMMENT ON COLUMN CO_BBS_CONF.TYPE_CD IS '유형_코드';
COMMENT ON COLUMN CO_BBS_CONF.FOLDER_NM IS '폴더_명';
COMMENT ON COLUMN CO_BBS_CONF.TABLE_NM IS '테이블_명';
COMMENT ON COLUMN CO_BBS_CONF.CMT_YN IS '의견_여부';
COMMENT ON COLUMN CO_BBS_CONF.CTG_YN IS '카테고리_여부';
COMMENT ON COLUMN CO_BBS_CONF.FILE_YN IS '파일_여부';
COMMENT ON COLUMN CO_BBS_CONF.FILE_CNT IS '파일_건수';
COMMENT ON COLUMN CO_BBS_CONF.OPEN_YN IS '공개_여부';
COMMENT ON COLUMN CO_BBS_CONF.NTC_YN IS '공지_여부';
COMMENT ON COLUMN CO_BBS_CONF.ADM_YN IS '관리자전용_여부';
COMMENT ON COLUMN CO_BBS_CONF.HTML_YN IS 'HTML_여부';
COMMENT ON COLUMN CO_BBS_CONF.ALIM_YN IS '알림_여부';
COMMENT ON COLUMN CO_BBS_CONF.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_BBS_CONF.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_BBS_CONF.MODI_DT IS '수정_일시';




CREATE TABLE CO_BBS_MGR
(
	BBS_CD               NUMBER(4) NOT NULL ,
	MGR_ID               VARCHAR2(20) NOT NULL ,
CONSTRAINT  PK_BBS_MGR PRIMARY KEY (BBS_CD,MGR_ID),
CONSTRAINT FK_BBS_MGR_BBS_CD FOREIGN KEY (BBS_CD) REFERENCES CO_BBS_CONF (BBS_CD) ON DELETE CASCADE,
CONSTRAINT FK_BBS_MGR_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE CASCADE
);



COMMENT ON TABLE CO_BBS_MGR IS '게시판_담당자';



COMMENT ON COLUMN CO_BBS_MGR.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS_MGR.MGR_ID IS '담당자_아이디';




CREATE TABLE CO_BBS_CTG
(
	BBS_CD               NUMBER(4) NOT NULL ,
	CTG_CD               NUMBER(4) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	CTG_NM               VARCHAR2(100) NOT NULL ,
CONSTRAINT  PK_BBS_CTG PRIMARY KEY (BBS_CD,CTG_CD),
CONSTRAINT FK_BBS_CTG_BBS_CD FOREIGN KEY (BBS_CD) REFERENCES CO_BBS_CONF (BBS_CD) ON DELETE CASCADE
);



COMMENT ON TABLE CO_BBS_CTG IS '게시판_카테고리';



COMMENT ON COLUMN CO_BBS_CTG.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS_CTG.CTG_CD IS '카테고리_코드';
COMMENT ON COLUMN CO_BBS_CTG.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_BBS_CTG.CTG_NM IS '카테고리_명';




CREATE TABLE CO_HDAY
(
	SEQ                  NUMBER NOT NULL ,
	HDAY_NM              VARCHAR2(100) NOT NULL ,
	START_DD             VARCHAR2(8) NULL ,
	END_DD               VARCHAR2(8) NULL ,
	LUNAR_YN             CHAR(1) DEFAULT  'N'  NOT NULL ,
	CYCLE                NUMBER(4) NOT NULL ,
	DOW                  NUMBER(1) NULL ,
	WEEK                 NUMBER(1) NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_HDAY PRIMARY KEY (SEQ)
);



COMMENT ON TABLE CO_HDAY IS '공휴일';



COMMENT ON COLUMN CO_HDAY.SEQ IS '일련번호';
COMMENT ON COLUMN CO_HDAY.HDAY_NM IS '공휴일_명';
COMMENT ON COLUMN CO_HDAY.START_DD IS '시작_일자';
COMMENT ON COLUMN CO_HDAY.END_DD IS '종료_일자';
COMMENT ON COLUMN CO_HDAY.LUNAR_YN IS '음력_여부';
COMMENT ON COLUMN CO_HDAY.CYCLE IS '주기';
COMMENT ON COLUMN CO_HDAY.DOW IS '요일';
COMMENT ON COLUMN CO_HDAY.WEEK IS '주';
COMMENT ON COLUMN CO_HDAY.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_HDAY.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_HDAY.MODI_DT IS '수정_일시';




CREATE TABLE CO_BBS
(
	BBS_CD               NUMBER(4) NOT NULL ,
	BBS_SEQ              NUMBER NOT NULL ,
	REF_SEQ              NUMBER DEFAULT  -1  NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	DEPTH                NUMBER(2) DEFAULT  0  NOT NULL ,
	CTG_CD               NUMBER(4) NULL ,
	TITLE                VARCHAR2(300) NOT NULL ,
	USER_KEY             VARCHAR2(100) NULL ,
	WRITER_NM            VARCHAR2(100) NOT NULL ,
	WRITER_ENC_PWD       VARCHAR2(100) NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	REPLY_NM             VARCHAR2(100) NULL ,
	QUESTION             CLOB NOT NULL ,
	REPLY                CLOB NULL ,
	ALERT_CDS            VARCHAR2(10) NULL ,
	STATUS_CD            VARCHAR2(20) DEFAULT  '-1'  NULL ,
	FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
	HTML_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	OPEN_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	DEL_YN               CHAR(1) DEFAULT  'N'  NOT NULL ,
	READ_CNT             NUMBER DEFAULT  0  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_BBS PRIMARY KEY (BBS_CD,BBS_SEQ),
CONSTRAINT FK_BBS_BBS_CD FOREIGN KEY (BBS_CD) REFERENCES CO_BBS_CONF (BBS_CD) ON DELETE CASCADE,
CONSTRAINT FK_BBS_USER_KEY FOREIGN KEY (USER_KEY) REFERENCES CO_USER (USER_KEY) ON DELETE SET NULL,
CONSTRAINT FK_BBS_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_BBS IS '게시판';



COMMENT ON COLUMN CO_BBS.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS.BBS_SEQ IS '게시판_일련번호';
COMMENT ON COLUMN CO_BBS.REF_SEQ IS '참조_일련번호';
COMMENT ON COLUMN CO_BBS.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_BBS.DEPTH IS '댓글_레벨';
COMMENT ON COLUMN CO_BBS.CTG_CD IS '카테고리_코드';
COMMENT ON COLUMN CO_BBS.TITLE IS '제목';
COMMENT ON COLUMN CO_BBS.USER_KEY IS '사용자_KEY';
COMMENT ON COLUMN CO_BBS.WRITER_NM IS '작성자_명';
COMMENT ON COLUMN CO_BBS.WRITER_ENC_PWD IS '작성자_암호화_비밀번호';
COMMENT ON COLUMN CO_BBS.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_BBS.REPLY_NM IS '답변자_명';
COMMENT ON COLUMN CO_BBS.QUESTION IS '질문';
COMMENT ON COLUMN CO_BBS.REPLY IS '답변';
COMMENT ON COLUMN CO_BBS.ALERT_CDS IS '통지_코드S';
COMMENT ON COLUMN CO_BBS.STATUS_CD IS '상태_코드';
COMMENT ON COLUMN CO_BBS.FILE_SEQ IS '파일_일련번호';
COMMENT ON COLUMN CO_BBS.HTML_YN IS 'HTML_여부';
COMMENT ON COLUMN CO_BBS.OPEN_YN IS '공개_여부';
COMMENT ON COLUMN CO_BBS.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN CO_BBS.READ_CNT IS '조회수';
COMMENT ON COLUMN CO_BBS.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_BBS.MODI_DT IS '수정_일시';




CREATE TABLE CO_BBS_COMMENT
(
	BBS_CD               NUMBER(4) NOT NULL ,
	BBS_SEQ              NUMBER NOT NULL ,
	CMT_SEQ              NUMBER NOT NULL ,
	REF_SEQ              NUMBER DEFAULT  -1  NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	DEPTH                NUMBER(2) DEFAULT  0  NOT NULL ,
	USER_KEY             VARCHAR2(100) NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	WRITER_NM            VARCHAR2(100) NOT NULL ,
	WRITER_ENC_PWD       VARCHAR2(100) NULL ,
	CMT_CONTENTS         VARCHAR2(4000) NOT NULL ,
	FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_BBS_COMMENT PRIMARY KEY (BBS_CD,BBS_SEQ,CMT_SEQ),
CONSTRAINT FK_BBS_COMMENT_BBS_CDBBS_ FOREIGN KEY (BBS_CD, BBS_SEQ) REFERENCES CO_BBS (BBS_CD, BBS_SEQ) ON DELETE CASCADE,
CONSTRAINT FK_BBS_COMMENT_USER_KEY FOREIGN KEY (USER_KEY) REFERENCES CO_USER (USER_KEY) ON DELETE SET NULL,
CONSTRAINT FK_BBS_COMMENT_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_BBS_COMMENT IS '게시판_코멘트';



COMMENT ON COLUMN CO_BBS_COMMENT.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS_COMMENT.BBS_SEQ IS '게시판_일련번호';
COMMENT ON COLUMN CO_BBS_COMMENT.CMT_SEQ IS '의견_일련번호';
COMMENT ON COLUMN CO_BBS_COMMENT.REF_SEQ IS '참조_일련번호';
COMMENT ON COLUMN CO_BBS_COMMENT.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_BBS_COMMENT.DEPTH IS '댓글_레벨';
COMMENT ON COLUMN CO_BBS_COMMENT.USER_KEY IS '사용자_KEY';
COMMENT ON COLUMN CO_BBS_COMMENT.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_BBS_COMMENT.WRITER_NM IS '작성자_명';
COMMENT ON COLUMN CO_BBS_COMMENT.WRITER_ENC_PWD IS '작성자_암호화_비밀번호';
COMMENT ON COLUMN CO_BBS_COMMENT.CMT_CONTENTS IS '의견_내용';
COMMENT ON COLUMN CO_BBS_COMMENT.FILE_SEQ IS '파일_일련번호';
COMMENT ON COLUMN CO_BBS_COMMENT.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_BBS_COMMENT.MODI_DT IS '수정_일시';




CREATE TABLE CO_BBS_NTC
(
    BBS_CD               NUMBER(4) NOT NULL ,
    NTC_SEQ              NUMBER NOT NULL ,
    MGR_ID               VARCHAR2(20 BYTE) NULL ,
    TITLE                VARCHAR2(300) NOT NULL ,
    CONTENTS             CLOB NOT NULL ,
    FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
    READ_CNT             NUMBER(6) DEFAULT  0  NOT NULL ,
    START_DD             VARCHAR2(8) NULL ,
    END_DD               VARCHAR2(8) NULL ,
    REG_DT               DATE DEFAULT SYSDATE  NOT NULL ,
    MODI_DT              DATE NULL ,
CONSTRAINT  PK_BBS_NTC PRIMARY KEY (BBS_CD,NTC_SEQ),
CONSTRAINT FK_BBS_NTC FOREIGN KEY (BBS_CD) REFERENCES CO_BBS_CONF (BBS_CD) ON DELETE CASCADE,
CONSTRAINT FK_BBS_NTC_MGR FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_BBS_NTC IS '게시판_공지';



COMMENT ON COLUMN CO_BBS_NTC.BBS_CD IS '게시판_코드';
COMMENT ON COLUMN CO_BBS_NTC.NTC_SEQ IS '공지_일련번호';
COMMENT ON COLUMN CO_BBS_NTC.MGR_ID IS '담당자_ID';
COMMENT ON COLUMN CO_BBS_NTC.TITLE IS '제목';
COMMENT ON COLUMN CO_BBS_NTC.CONTENTS IS '내용';
COMMENT ON COLUMN CO_BBS_NTC.FILE_SEQ IS '파일_순번';
COMMENT ON COLUMN CO_BBS_NTC.READ_CNT IS '조회_수';
COMMENT ON COLUMN CO_BBS_NTC.START_DD IS '시작_일자';
COMMENT ON COLUMN CO_BBS_NTC.END_DD IS '종료_일자';
COMMENT ON COLUMN CO_BBS_NTC.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_BBS_NTC.MODI_DT IS '수정_일시';




CREATE TABLE CO_AUTH_ASSIGN_LOG
(
	MGR_ID               VARCHAR2(20) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	LOG_CONTENTS         VARCHAR2(1000) NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
CONSTRAINT  PK_AUTH_ASSIGN_LOG PRIMARY KEY (MGR_ID,ORDER_NO),
CONSTRAINT FK_AUTH_ASSIGN_LOG_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE CASCADE
);



COMMENT ON TABLE CO_AUTH_ASSIGN_LOG IS '권한_할당_로그';



COMMENT ON COLUMN CO_AUTH_ASSIGN_LOG.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_AUTH_ASSIGN_LOG.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_AUTH_ASSIGN_LOG.LOG_CONTENTS IS '로그_내용';
COMMENT ON COLUMN CO_AUTH_ASSIGN_LOG.REG_DT IS '등록_일시';




CREATE TABLE CO_AUTH_ASSIGN
(
	AUTH_CD              NUMBER(4) NOT NULL ,
	MGR_ID               VARCHAR2(20) NOT NULL ,
CONSTRAINT  PK_AUTH_ASSIGN PRIMARY KEY (AUTH_CD,MGR_ID),
CONSTRAINT FK_AUTH_ASSIGN_AUTH_CD FOREIGN KEY (AUTH_CD) REFERENCES CO_AUTH (AUTH_CD) ON DELETE CASCADE,
CONSTRAINT FK_AUTH_ASSIGN_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE CASCADE
);



COMMENT ON TABLE CO_AUTH_ASSIGN IS '권한_할당';



COMMENT ON COLUMN CO_AUTH_ASSIGN.AUTH_CD IS '권한_코드';
COMMENT ON COLUMN CO_AUTH_ASSIGN.MGR_ID IS '담당자_아이디';




CREATE TABLE CO_AUTH_ITEM
(
	AUTH_CD              NUMBER(4) NOT NULL ,
	MENU_CD              NUMBER(4) NOT NULL ,
	READ_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	CREATE_YN            CHAR(1) DEFAULT  'N'  NOT NULL ,
	UPDATE_YN            CHAR(1) DEFAULT  'N'  NOT NULL ,
	DELETE_YN            CHAR(1) DEFAULT  'N'  NOT NULL ,
CONSTRAINT  PK_AUTH_ITEM PRIMARY KEY (AUTH_CD,MENU_CD),
CONSTRAINT FK_AUTH_ITEM_AUTH_CD FOREIGN KEY (AUTH_CD) REFERENCES CO_AUTH (AUTH_CD) ON DELETE CASCADE,
CONSTRAINT FK_AUTH_ITEM_MENU_CD FOREIGN KEY (MENU_CD) REFERENCES CO_MENU (MENU_CD) ON DELETE CASCADE
);



COMMENT ON TABLE CO_AUTH_ITEM IS '권한_항목';



COMMENT ON COLUMN CO_AUTH_ITEM.AUTH_CD IS '권한_코드';
COMMENT ON COLUMN CO_AUTH_ITEM.MENU_CD IS '메뉴_코드';
COMMENT ON COLUMN CO_AUTH_ITEM.READ_YN IS '조회_여부';
COMMENT ON COLUMN CO_AUTH_ITEM.CREATE_YN IS 'CREATE_여부';
COMMENT ON COLUMN CO_AUTH_ITEM.UPDATE_YN IS 'UPDATE_여부';
COMMENT ON COLUMN CO_AUTH_ITEM.DELETE_YN IS 'DELETE_여부';




CREATE TABLE CO_FILE
(
	FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
	FILE_ID              VARCHAR2(50) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	FILE_NM              VARCHAR2(200) NOT NULL ,
	ORG_FILE_NM          VARCHAR2(200) NOT NULL ,
	FILE_PATH            VARCHAR2(300) NOT NULL ,
	FILE_URL             VARCHAR2(200) NOT NULL ,
	FILE_SIZE            VARCHAR2(20) NOT NULL ,
	FILE_TYPE            VARCHAR2(100) NOT NULL ,
	EXTENSION            VARCHAR2(20) NOT NULL ,
	INPUT_NM             VARCHAR2(20) NOT NULL ,
	DOWN_CNT             NUMBER DEFAULT  0  NOT NULL ,
CONSTRAINT  PK_FILE PRIMARY KEY (FILE_SEQ,FILE_ID)
);



COMMENT ON TABLE CO_FILE IS '파일';



COMMENT ON COLUMN CO_FILE.FILE_SEQ IS '파일_일련번호';
COMMENT ON COLUMN CO_FILE.FILE_ID IS '파일_아이디';
COMMENT ON COLUMN CO_FILE.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_FILE.FILE_NM IS '파일_명';
COMMENT ON COLUMN CO_FILE.ORG_FILE_NM IS '원본_파일_명';
COMMENT ON COLUMN CO_FILE.FILE_PATH IS '파일_경로';
COMMENT ON COLUMN CO_FILE.FILE_URL IS '파일_URL';
COMMENT ON COLUMN CO_FILE.FILE_SIZE IS '파일_크기';
COMMENT ON COLUMN CO_FILE.FILE_TYPE IS '파일_유형';
COMMENT ON COLUMN CO_FILE.EXTENSION IS '확장자';
COMMENT ON COLUMN CO_FILE.INPUT_NM IS '입력_명';
COMMENT ON COLUMN CO_FILE.DOWN_CNT IS '다운로드_건수';




CREATE TABLE CO_FILE_LOG
(
	FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
	FILE_ID              VARCHAR2(50) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	WORKER_ID            VARCHAR2(100) NOT NULL ,
	WORKER_NM            VARCHAR2(50) NOT NULL ,
	DOWN_CNT             NUMBER DEFAULT  1  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
CONSTRAINT  PK_FILE_LOG PRIMARY KEY (FILE_SEQ,FILE_ID,ORDER_NO),
CONSTRAINT FK_FILE_LOG_FILE_SEQFI FOREIGN KEY (FILE_SEQ, FILE_ID) REFERENCES CO_FILE (FILE_SEQ, FILE_ID) ON DELETE CASCADE
);



COMMENT ON TABLE CO_FILE_LOG IS '파일_로그';



COMMENT ON COLUMN CO_FILE_LOG.FILE_SEQ IS '파일_일련번호';
COMMENT ON COLUMN CO_FILE_LOG.FILE_ID IS '파일_아이디';
COMMENT ON COLUMN CO_FILE_LOG.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_FILE_LOG.WORKER_ID IS '작업자_아이디';
COMMENT ON COLUMN CO_FILE_LOG.WORKER_NM IS '작업자_명';
COMMENT ON COLUMN CO_FILE_LOG.DOWN_CNT IS '다운로드_건수';
COMMENT ON COLUMN CO_FILE_LOG.REG_DT IS '등록_일시';




CREATE TABLE CO_FAQ_CTG
(
	CTG_CD               NUMBER(4) NOT NULL ,
	HIGH_CTG_CD          NUMBER(4) NULL ,
	CTG_NM               VARCHAR2(100) NOT NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_FAQ_CTG PRIMARY KEY (CTG_CD),
CONSTRAINT FK_FAQ_CTG_HIGH_CTG_CD FOREIGN KEY (HIGH_CTG_CD) REFERENCES CO_FAQ_CTG (CTG_CD) ON DELETE SET NULL
);



COMMENT ON TABLE CO_FAQ_CTG IS 'FAQ_카테고리';



COMMENT ON COLUMN CO_FAQ_CTG.CTG_CD IS '카테고리_코드';
COMMENT ON COLUMN CO_FAQ_CTG.HIGH_CTG_CD IS '상위_카테고리_코드';
COMMENT ON COLUMN CO_FAQ_CTG.CTG_NM IS '카테고리_명';
COMMENT ON COLUMN CO_FAQ_CTG.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_FAQ_CTG.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_FAQ_CTG.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_FAQ_CTG.MODI_DT IS '수정_일시';




CREATE TABLE CO_FAQ
(
	SEQ                  NUMBER NOT NULL ,
	CTG_CD               NUMBER(4) NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	TITLE                VARCHAR2(300) NOT NULL ,
	CONTENTS             CLOB NOT NULL ,
	FILE_SEQ             NUMBER DEFAULT  -1  NOT NULL ,
	RECOM_CNT            NUMBER DEFAULT  0  NOT NULL ,
	OPP_CNT              NUMBER DEFAULT  0  NOT NULL ,
	READ_CNT             NUMBER DEFAULT  0  NOT NULL ,
	APRV_YN              CHAR(1) DEFAULT  'N'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_FAQ PRIMARY KEY (SEQ),
CONSTRAINT FK_FAQ_CTG_CD FOREIGN KEY (CTG_CD) REFERENCES CO_FAQ_CTG (CTG_CD) ON DELETE SET NULL,
CONSTRAINT FK_FAQ_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_FAQ IS 'FAQ';



COMMENT ON COLUMN CO_FAQ.SEQ IS '일련번호';
COMMENT ON COLUMN CO_FAQ.CTG_CD IS '카테고리_코드';
COMMENT ON COLUMN CO_FAQ.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_FAQ.TITLE IS '제목';
COMMENT ON COLUMN CO_FAQ.CONTENTS IS '내용';
COMMENT ON COLUMN CO_FAQ.FILE_SEQ IS '파일_일련번호';
COMMENT ON COLUMN CO_FAQ.RECOM_CNT IS '추천_건수';
COMMENT ON COLUMN CO_FAQ.OPP_CNT IS '반대_건수';
COMMENT ON COLUMN CO_FAQ.READ_CNT IS '조회수';
COMMENT ON COLUMN CO_FAQ.APRV_YN IS '승인_여부';
COMMENT ON COLUMN CO_FAQ.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_FAQ.MODI_DT IS '수정_일시';




CREATE TABLE CO_CODE_GRP
(
	GRP_CD               VARCHAR2(20) NOT NULL ,
	GRP_NM               VARCHAR2(100) NOT NULL ,
CONSTRAINT  PK_CODE_GRP PRIMARY KEY (GRP_CD)
);



COMMENT ON TABLE CO_CODE_GRP IS '코드_그룹';



COMMENT ON COLUMN CO_CODE_GRP.GRP_CD IS '그룹_코드';
COMMENT ON COLUMN CO_CODE_GRP.GRP_NM IS '그룹_명';




CREATE TABLE CO_CODE_PRV
(
	GRP_CD               VARCHAR2(20) NOT NULL ,
	PRV_CD               VARCHAR2(20) NOT NULL ,
	SUB_GRP_CD           VARCHAR2(20) NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	PRV_NM               VARCHAR2(100) NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_CODE_PRV PRIMARY KEY (GRP_CD,PRV_CD),
CONSTRAINT FK_CODE_PRV_GRP_CD FOREIGN KEY (GRP_CD) REFERENCES CO_CODE_GRP (GRP_CD) ON DELETE CASCADE,
CONSTRAINT FK_CODE_PRV_SUB_GRP_CD FOREIGN KEY (SUB_GRP_CD) REFERENCES CO_CODE_GRP (GRP_CD) ON DELETE SET NULL
);



COMMENT ON TABLE CO_CODE_PRV IS '코드_개별';



COMMENT ON COLUMN CO_CODE_PRV.GRP_CD IS '그룹_코드';
COMMENT ON COLUMN CO_CODE_PRV.PRV_CD IS '개별_코드';
COMMENT ON COLUMN CO_CODE_PRV.SUB_GRP_CD IS '하위_그룹_코드';
COMMENT ON COLUMN CO_CODE_PRV.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_CODE_PRV.PRV_NM IS '개별_명';
COMMENT ON COLUMN CO_CODE_PRV.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_CODE_PRV.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_CODE_PRV.MODI_DT IS '수정_일시';




CREATE TABLE CO_MGR_ABSENCE
(
	MGR_ID               VARCHAR2(20) NOT NULL ,
	AGENCY_ID            VARCHAR2(20) NULL ,
	START_DT             DATE NOT NULL ,
	END_DT               DATE NOT NULL ,
	ABSENCE_CD           VARCHAR2(20) NOT NULL ,
	ABSENCE_REASON       VARCHAR2(300) NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_MGR_ABSENCE PRIMARY KEY (MGR_ID),
CONSTRAINT FK_MGR_ABSENCE_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE CASCADE,
CONSTRAINT FK_MGR_ABSENCE_AGENCY_ID FOREIGN KEY (AGENCY_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_MGR_ABSENCE IS '담당자_부재';



COMMENT ON COLUMN CO_MGR_ABSENCE.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_MGR_ABSENCE.AGENCY_ID IS '대리인_아이디';
COMMENT ON COLUMN CO_MGR_ABSENCE.START_DT IS '시작_일시';
COMMENT ON COLUMN CO_MGR_ABSENCE.END_DT IS '종료_일시';
COMMENT ON COLUMN CO_MGR_ABSENCE.ABSENCE_CD IS '부재_코드';
COMMENT ON COLUMN CO_MGR_ABSENCE.ABSENCE_REASON IS '부재_사유';
COMMENT ON COLUMN CO_MGR_ABSENCE.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_MGR_ABSENCE.MODI_DT IS '수정_일시';




CREATE TABLE CO_DOMAIN
(
	DOMAIN_CD            NUMBER(4) NOT NULL ,
	DOMAIN_NM            VARCHAR2(100) NOT NULL ,
	DOMAIN_URL           VARCHAR2(50) NOT NULL ,
CONSTRAINT  PK_DOMAIN PRIMARY KEY (DOMAIN_CD)
);



COMMENT ON TABLE CO_DOMAIN IS '도메인';



COMMENT ON COLUMN CO_DOMAIN.DOMAIN_CD IS '도메인_코드';
COMMENT ON COLUMN CO_DOMAIN.DOMAIN_NM IS '도메인_명';
COMMENT ON COLUMN CO_DOMAIN.DOMAIN_URL IS '도메인_URL';




CREATE TABLE CO_MENU_FRONT
(
	MENU_CD              NUMBER(4) NOT NULL ,
	DOMAIN_CD            NUMBER(4) NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	HIGH_MENU_CD         NUMBER(4) NULL ,
	ORDER_NO             NUMBER(4) DEFAULT  0  NOT NULL ,
	MENU_NM              VARCHAR2(50) NOT NULL ,
	MENU_URL             VARCHAR2(200) NULL ,
	MENU_PATTERN         VARCHAR2(50) NULL ,
	MENU_ID              VARCHAR2(40) NULL ,
	MENU_ICON            VARCHAR2(30) NULL ,
	TYPE_CD              VARCHAR2(20) NULL ,
	SHOW_YN              CHAR(1) DEFAULT  'Y'  NOT NULL ,
	USE_YN               CHAR(1) DEFAULT  'Y'  NOT NULL ,
	REG_DT               DATE DEFAULT  SYSDATE  NOT NULL ,
	MODI_DT              DATE NULL ,
CONSTRAINT  PK_MENU_FRONT PRIMARY KEY (MENU_CD),
CONSTRAINT FK_MENU_FRONT_HIGH_MENU_CD FOREIGN KEY (HIGH_MENU_CD) REFERENCES CO_MENU_FRONT (MENU_CD) ON DELETE CASCADE,
CONSTRAINT FK_MENU_FRONT_DOMAIN_CD FOREIGN KEY (DOMAIN_CD) REFERENCES CO_DOMAIN (DOMAIN_CD) ON DELETE SET NULL,
CONSTRAINT FK_MENU_FRONT_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES CO_MGR (MGR_ID) ON DELETE SET NULL
);



COMMENT ON TABLE CO_MENU_FRONT IS '메뉴_프론트';



COMMENT ON COLUMN CO_MENU_FRONT.MENU_CD IS '메뉴_코드';
COMMENT ON COLUMN CO_MENU_FRONT.DOMAIN_CD IS '도메인_코드';
COMMENT ON COLUMN CO_MENU_FRONT.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_MENU_FRONT.HIGH_MENU_CD IS '상위_메뉴_코드';
COMMENT ON COLUMN CO_MENU_FRONT.ORDER_NO IS '정렬_순서';
COMMENT ON COLUMN CO_MENU_FRONT.MENU_NM IS '메뉴_명';
COMMENT ON COLUMN CO_MENU_FRONT.MENU_URL IS '메뉴_URL';
COMMENT ON COLUMN CO_MENU_FRONT.MENU_PATTERN IS '메뉴_패턴';
COMMENT ON COLUMN CO_MENU_FRONT.MENU_ID IS '메뉴_아이디';
COMMENT ON COLUMN CO_MENU_FRONT.MENU_ICON IS '메뉴_아이콘';
COMMENT ON COLUMN CO_MENU_FRONT.TYPE_CD IS '유형_코드';
COMMENT ON COLUMN CO_MENU_FRONT.SHOW_YN IS '표시_여부';
COMMENT ON COLUMN CO_MENU_FRONT.USE_YN IS '사용_여부';
COMMENT ON COLUMN CO_MENU_FRONT.REG_DT IS '등록_일시';
COMMENT ON COLUMN CO_MENU_FRONT.MODI_DT IS '수정_일시';



CREATE TABLE CO_LOGIN_LOG
(
	LOG_SEQ              NUMBER NOT NULL ,
	MGR_ID               VARCHAR2(20) NULL ,
	AGENCY_ID            VARCHAR2(20) NULL ,
	IP_ADDR              VARCHAR2(20) NULL ,
	LOGIN_DT             DATE NULL ,
	LOGOUT_DT            DATE NULL ,
CONSTRAINT  PK_LOGIN_LOG PRIMARY KEY (LOG_SEQ)
);



COMMENT ON TABLE CO_LOGIN_LOG IS '로그인_로그';



COMMENT ON COLUMN CO_LOGIN_LOG.LOG_SEQ IS '로그_일련번호';
COMMENT ON COLUMN CO_LOGIN_LOG.MGR_ID IS '담당자_아이디';
COMMENT ON COLUMN CO_LOGIN_LOG.AGENCY_ID IS '대리인_아이디';
COMMENT ON COLUMN CO_LOGIN_LOG.IP_ADDR IS 'IP_주소';
COMMENT ON COLUMN CO_LOGIN_LOG.LOGIN_DT IS '로그인_일시';
COMMENT ON COLUMN CO_LOGIN_LOG.LOGOUT_DT IS '로그아웃_일시';



/* IpFilterInterceptor 사용할때만 생성 */
CREATE TABLE SI_IP_FILTER
(
    IP_SEQ      NUMBER NOT NULL, 
    IP_NM       VARCHAR2(100) NOT NULL, 
    START_IP    VARCHAR2(20), 
    END_IP      VARCHAR2(20), 
    REG_ID      VARCHAR2(20), 
    REG_DT      DATE NULL, 
    MODI_DT     DATE NULL, 
    USE_YN      CHAR(1) DEFAULT  'Y'  NOT NULL ,
    CONSTRAINT  PK_IP PRIMARY KEY (IP_SEQ)
);



COMMENT ON TABLE SI_IP_FILTER IS 'IP필터';



COMMENT ON COLUMN SI_IP_FILTER.IP_SEQ IS 'IP_일련번호';
COMMENT ON COLUMN SI_IP_FILTER.IP_NM IS 'IP_명';
COMMENT ON COLUMN SI_IP_FILTER.START_IP IS '시작_IP';
COMMENT ON COLUMN SI_IP_FILTER.END_IP IS '종료_IP';
COMMENT ON COLUMN SI_IP_FILTER.REG_ID IS '등록_아이디';
COMMENT ON COLUMN SI_IP_FILTER.REG_DT IS '등록_일시';
COMMENT ON COLUMN SI_IP_FILTER.MODI_DT IS '수정_일시';
COMMENT ON COLUMN SI_IP_FILTER.USE_YN IS '사용_여부';
